#!/bin/bash

HERE=`pwd`
TARGETS='lucid maverick natty oneiric'
#PUBLISH='PALASO'
#PUBLISH='LINGNET'
VARIANT='lingnet'
REVISION=`echo $BUILD_NUMBER | sed -e 's/[:-].*$//'`
PRODUCT='wsedit'
BASE=`cat ../bld/version.txt`
ZIPTYPE='gz'
DEST=../output

cp ../building/${PRODUCT}-${BASE}.tar.gz ~/upstream/${PRODUCT}_${BASE}.orig.tar.gz

source /home/bob/pbuilder/build.common
